version: '3.8'

services:
  spanaflask:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/usr/src/web
    ports:
      - "8000:5000"
  db:
    image: postgres:16
    container_name: spanaflask-db
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./postgresData:/var/lib/postgresql/data
    ports:
      - "5123:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres-U $${POSTGRES_USER} -d $${POSTGRES_DB} -t 1"]
      interval: 10s
      timeout: 5s
      retries: 3
  rediscont:
    image: redis:alpine
    container_name: spanaflask-redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redisData:/data

volumes:
  postgresData:
  redisData:

