"""empty message

Revision ID: 40d5280c21e1
Revises: 282975b0715f
Create Date: 2024-03-16 21:44:28.773285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40d5280c21e1'
down_revision = '282975b0715f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave',
    sa.Column('leaveType', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('startDate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('endDate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('moderator', sa.String(), nullable=True),
    sa.Column('moderatorNote', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('userId', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.alter_column('userId',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.alter_column('userId',
               existing_type=sa.UUID(),
               nullable=False)

    op.drop_table('leave')
    # ### end Alembic commands ###
