"""empty message

Revision ID: ff6afed1f01a
Revises: 651466e9f873
Create Date: 2024-03-21 10:30:15.029740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff6afed1f01a'
down_revision = '651466e9f873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('manager', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', 'MODERATOR', name='usertype'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['userId'], ['id'])

    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.create_foreign_key(None, 'user', ['userId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('user')
    # ### end Alembic commands ###
